// Code generated by mockery v2.30.16. DO NOT EDIT.

package mock

import (
	model "movierental/model"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetMovieById provides a mock function with given fields: id
func (_m *Client) GetMovieById(id string) (*model.ClientMovieResponse, error) {
	ret := _m.Called(id)

	var r0 *model.ClientMovieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ClientMovieResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ClientMovieResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientMovieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
