// Code generated by MockGen. DO NOT EDIT.
// Source: service/price.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "movieRentals/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPriceService is a mock of IPriceService interface.
type MockIPriceService struct {
	ctrl     *gomock.Controller
	recorder *MockIPriceServiceMockRecorder
}

// MockIPriceServiceMockRecorder is the mock recorder for MockIPriceService.
type MockIPriceServiceMockRecorder struct {
	mock *MockIPriceService
}

// NewMockIPriceService creates a new mock instance.
func NewMockIPriceService(ctrl *gomock.Controller) *MockIPriceService {
	mock := &MockIPriceService{ctrl: ctrl}
	mock.recorder = &MockIPriceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPriceService) EXPECT() *MockIPriceServiceMockRecorder {
	return m.recorder
}

// PriceItem mocks base method.
func (m *MockIPriceService) PriceItem(ctx context.Context, items []model.PricingItem) (*model.PricingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceItem", ctx, items)
	ret0, _ := ret[0].(*model.PricingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PriceItem indicates an expected call of PriceItem.
func (mr *MockIPriceServiceMockRecorder) PriceItem(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceItem", reflect.TypeOf((*MockIPriceService)(nil).PriceItem), ctx, items)
}
