version: '3.1'
services:
  postgres:
    image: "postgres:13.4"
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_db
    ports:
      - 5432:5432