// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"time"
)

type Movie struct {
	ID       string
	Title    string
	Released time.Time
	Genre    string
	Actors   string
	Year     int32
	Price    int64
	Quantity int32
}
